package ej15;
import java.util.Scanner;

public class ej15 {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		
		String tectoCompleto = "\r\n"
				+ "“Lorem fistrum diodenoo la caidita a gramenawer la caidita ahorarr a wan.\r\n"
				+ "\r\n"
				+ "Jarl sexuarl a wan me cago en tus muelas te voy a borrar el cerito por la gloria\r\n"
				+ "\r\n"
				+ " de mi madre está la cosa muy malar benemeritaar mamaar va usté muy cargadoo.\r\n"
				+ "\r\n"
				+ " Condemor diodeno jarl no puedor está la cosa muy malar qué dise usteer te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa pecador la caidita qué dise usteer. No te digo trigo por no\r\n"
				+ "\r\n"
				+ " llamarte Rodrigor me cago en tus muelas pupita ahorarr quietooor amatomaa\r\n"
				+ "\r\n"
				+ " ahorarr se calle ustée me cago en tuLeticiaGarcia 7s muelas. A gramenawer\r\n"
				+ "\r\n"
				+ " apetecan por la gloria de mi madre me cago en tus muelas pupita. Llevame al sircoo\r\n"
				+ "\r\n"
				+ " te va a hasé pupitaa ahorarr tiene musho peligro qué dise usteer tiene musho\r\n"
				+ "\r\n"
				+ " peligro hasta luego Lucas se calle ustée torpedo. Te va a hasé pupitaa está la\r\n"
				+ "\r\n"
				+ " cosa muy malar amatomaa no te digo trigo por no llamarte Rodrigor ahorarr no puedor\r\n"
				+ "\r\n"
				+ " sexuarl a wan de la pradera la caidita pecador.\r\n"
				+ "\r\n"
				+ "Apetecan a gramenawer está la cosa muy malar llevame al sircoo amatomaa ese pedazo\r\n"
				+ "\r\n"
				+ "de llevame al sircoo. Me cago en tus muelas no puedor ahorarr diodeno te voy a borrar\r\n"
				+ "\r\n"
				+ " el cerito papaar papaar torpedo no puedor ese que llega llevame al sircoo. No puedor\r\n"
				+ "\r\n"
				+ " ese que llega jarl quietooor pupita. Hasta luego Lucas a peich amatomaa mamaar te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa ese hombree. Te voy a borrar el cerito la caidita está la cosa muy malar\r\n"
				+ "\r\n"
				+ " diodeno está la cosa muy malar. Jarl a peich condemor pecador.\r\n"
				+ "\r\n"
				+ "Jarl la caidita de la pradera qué dise usteer sexuarl condemor. Fistro a gramenawer va\r\n"
				+ "\r\n"
				+ " usté muy cargadoo te va a hasé pupitaa diodenoo. Se calle ustée al ataquerl se calle\r\n"
				+ "\r\n"
				+ " ustée te voy a borrar el cerito a peich jarl tiene musho peligro papaar papaar de la\r\n"
				+ "\r\n"
				+ " pradera a gramenawer no puedor. Diodeno al ataquerl a wan hasta luego Lucas apetecan\r\n"
				+ "\r\n"
				+ " jarl. Va usté muy cargadoo llevame al sircoo se calle ustée por la gloria de mi madre\r\n"
				+ "\r\n"
				+ " fistro. Jarl a peich no te digo trigo por no llamarte Rodrigor ese hombree la caidita.\r\n"
				+ "\r\n"
				+ " Ahorarr a wan fistro al ataquerl diodenoo ese pedazo de jarl llevame al sircoo.\r\n"
				+ "\r\n"
				+ " Tiene musho peligro mamaar condemor amatomaa me cago en tus muelas torpedo a gramenawer\r\n"
				+ "\r\n"
				+ " tiene musho peligro de la pradera papaar papaar. Pecador pupita mamaar pupita quietooor\r\n"
				+ "\r\n"
				+ " qué dise usteer fistro caballo blanco caballo negroorl papaar papaar.Lorem fistrum diodenoo la caidita a gramenawer la caidita ahorarr a wan.\r\n"
				+ "\r\n"
				+ "Jarl sexuarl a wan me cago en tus muelas te voy a borrar el cerito por la gloria\r\n"
				+ "\r\n"
				+ " de mi madre está la cosa muy malar benemeritaar mamaar va usté muy cargadoo.\r\n"
				+ "\r\n"
				+ " Condemor diodeno jarl no puedor está la cosa muy malar qué dise usteer te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa pecador la caidita qué dise usteer. No te digo trigo por no\r\n"
				+ "\r\n"
				+ " llamarte Rodrigor me cago en tus muelas pupita ahorarr quietooor amatomaa\r\n"
				+ "\r\n"
				+ " ahorarr se calle ustée me cago en tus muelas sexuarl. A gramenawer\r\n"
				+ "\r\n"
				+ " apetecan por la gloria de mi madre me cago en tus muelas pupita. Llevame al sircoo\r\n"
				+ "\r\n"
				+ " te va a hasé pupitaa ahorarr tiene musho peligro qué dise usteer tiene musho\r\n"
				+ "\r\n"
				+ " peligro hasta luego Lucas se calle JuanjoMedina 6 ustée torpedo. Te va a hasé pupitaa está la\r\n"
				+ "\r\n"
				+ " cosa muy malar amatomaa no te digo trigo por no llamarte Rodrigor ahorarr no puedor\r\n"
				+ "\r\n"
				+ " sexuarl a wan de la pradera la caidita pecador.\r\n"
				+ "\r\n"
				+ "Apetecan a gramenawer está la cosa muy malar llevame al sircoo amatomaa ese pedazo\r\n"
				+ "\r\n"
				+ "de llevame al sircoo. Me cago en tus muelas no puedor ahorarr diodeno te voy a borrar\r\n"
				+ "\r\n"
				+ " el cerito papaar papaar torpedo no puedor ese que llega llevame al sircoo. No puedor\r\n"
				+ "\r\n"
				+ " ese que llega jarl quietooor pupita. Hasta luego Lucas a peich amatomaa mamaar te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa ese hombree. Te voy a borrar el cerito la caidita está la cosa muy malar\r\n"
				+ "\r\n"
				+ " diodeno está la cosa muy malar. Jarl a peich condemor pecador.\r\n"
				+ "\r\n"
				+ "Jarl la caidita de la pradera qué dise usteer sexuarl condemor. Fistro a gramenawer va\r\n"
				+ "\r\n"
				+ " usté muy cargadoo te va a hasé pupitaa diodenoo. Se calle ustée al ataquerl se calle\r\n"
				+ "\r\n"
				+ " ustée te voy a borrar el cerito a peich jarl tiene musho peligro papaar papaar de la\r\n"
				+ "\r\n"
				+ " pradera a gramenawer no puedor. Diodeno al ataquerl a wan hasta luego Lucas apetecan\r\n"
				+ "\r\n"
				+ " jarl. Va usté muy cargadoo llevame al sircoo se calle ustée por la gloria de mi madre\r\n"
				+ "\r\n"
				+ " fistro. Jarl a peich no te digo trigo por no llamarte Rodrigor ese hombree la caidita.\r\n"
				+ "\r\n"
				+ " Ahorarr a wan fistro al ataquerl diodenoo ese pedazo de jarl llevame al sircoo.\r\n"
				+ "\r\n"
				+ " Tiene musho peligro mamaar EricMorata 8condemor amatomaa me cago en tus muelas torpedo a gramenawer\r\n"
				+ "\r\n"
				+ " tiene musho peligro de la pradera papaar papaar. Pecador pupita mamaar pupita quietooor\r\n"
				+ "\r\n"
				+ " qué dise usteer fistro caAlexisGarcia 8ballo blancoGuillermoCamino 2caballo negroorl papaar papaar.Lorem fistrum diodenoo la caidita a gramenawer la caidita ahorarr a wan.\r\n"
				+ "\r\n"
				+ "Jarl sexuarl a wan me cago en tus muelas te voy a borrar el cerito por la gloria\r\n"
				+ "\r\n"
				+ " de mi madre está la cosa muy malar benemeritaar mamaar va usté muy cargadoo.\r\n"
				+ "\r\n"
				+ " Condemor diodeno jarl no puedor está la cosa muy malar qué dise usteer te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa pecador la caidita qué dise usteer. No te digo trigo por no\r\n"
				+ "\r\n"
				+ " llamarte Rodrigor me cago en tus muelas pupita ahorarr quietooor amatomaa\r\n"
				+ "\r\n"
				+ " ahorarr se calle ustée me cago en tus muelas sexuarl. A gramenawer\r\n"
				+ "\r\n"
				+ " apetecan por la gloria de mi madre me cago en tus muelas pupita. Llevame al sircoo\r\n"
				+ "\r\n"
				+ " te va a hasé pupitaa ahorarr tiene musho peligro qué dise usteer tiene musho\r\n"
				+ "\r\n"
				+ " peligro hasta luego Lucas se calle ustée torpedo. Te va a hasé pupitaa está la\r\n"
				+ "\r\n"
				+ " cosa muy malar amatomaa no te digo trigo por no llamarte Rodrigor ahorarr no puedor\r\n"
				+ "\r\n"
				+ " sexuarl a wan de la pradera la caidita pecador.\r\n"
				+ "\r\n"
				+ "Apetecan a gramenawer está la cosa muy malar llevame al sircoo amatomaa ese pedazo\r\n"
				+ "\r\n"
				+ "de llevame al sircoo. Me cago en tus muelas no puedor ahorarr diodeno te voy a borrar\r\n"
				+ "\r\n"
				+ " el cerito papaar papaar torpedo no puedor ese que llega llevame al sircoo. No puedor\r\n"
				+ "\r\n"
				+ " ese que llega jarl quietooor pupita. Hasta luego Lucas a peich amatomaa mamaar te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa ese hombree. Te voy a borrar el cerito la caidita está la cosa muy malar\r\n"
				+ "\r\n"
				+ " diodeno está la cosa muy malar. Jarl a peich condemor pecador.\r\n"
				+ "\r\n"
				+ "Jarl la caidita de la pradera qué dise usteer sexuarl condemor. Fistro a gramenawer va\r\n"
				+ "\r\n"
				+ " usté muy cargadoo te va a hasé pupitaa diodenoo. Se calle ustée al ataquerl se calle\r\n"
				+ "\r\n"
				+ " ustée te voy a borrar el cerito a peich jarl tiene musho peligro papaar papaar de la\r\n"
				+ "\r\n"
				+ " pradera a gramenawer no puedor. Diodeno al ataquerl a wan hasta luego Lucas apetecan\r\n"
				+ "\r\n"
				+ " jarl. Va usté muy cargadoo llevame al sircoo se calle ustée por la gloria de mi madre\r\n"
				+ "\r\n"
				+ " fistro. Jarl a peich no te digo trigo por no llamarte Rodrigor ese hombree la caidita.\r\n"
				+ "\r\n"
				+ " Ahorarr a wan fistro al ataquerl diodenoo ese pedazo de jarl llevame al sircoo.\r\n"
				+ "\r\n"
				+ " Tiene musho peligro mamaar condemor amatomaa me cago en tus muelas torpedo a gramenawer\r\n"
				+ "\r\n"
				+ " tiene musho peligro de la pradera papaar papaar. Pecador pupita mamaar pupita quietooor\r\n"
				+ "\r\n"
				+ " qué dise usteer fistro caballo blanco caballo negroorl papaar papaar.Lorem fistrum diodenoo la caidita a gramenawer la caidita ahorarr a wan.\r\n"
				+ "\r\n"
				+ "Jarl sexuarl a wan me cago en tus muelas te voy a borrar el cerito por la gloria\r\n"
				+ "\r\n"
				+ " de mi madre está la cosa muy malar benemeritaar mamaar va usté muy cargadoo.\r\n"
				+ "\r\n"
				+ " Condemor diodeno jarl no puedor está la cosa muy malar qué dise usteer te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa pecador la caidita qué dise usteer. No te digo trigo por no\r\n"
				+ "\r\n"
				+ " llamarte Rodrigor me cago en tus muelas pupita ahorarr quietooor amatomaa\r\n"
				+ "\r\n"
				+ " ahorarr se calle ustée me cago en tus muelas sexuarl. A gramenawer\r\n"
				+ "\r\n"
				+ " apetecan por la gloria de mi madre me cago en tus muelas pupita. Llevame al sircoo\r\n"
				+ "\r\n"
				+ " te va a hasé pupitaa ahorarr tiene musho peligro qué dise usteer tiene musho\r\n"
				+ "\r\n"
				+ " peligro hasta luego Lucas se calle ustéAntonioRodriguez 5e torpedo. Te va a hasé pupitaa está la\r\n"
				+ "\r\n"
				+ " cosa muy malar amatomaa no te digo trigo por no llamarte Rodrigor ahorarr no puedor\r\n"
				+ "\r\n"
				+ " sexuarl a wan de la pradera la caidita pecador.\r\n"
				+ "\r\n"
				+ "Apetecan a gramenawer está la cosa muy malar llevame al sircoo amatomaa ese pedazo\r\n"
				+ "\r\n"
				+ "de llevame al sircoo. Me cago en tus muelas no puedor ahorarr diodeno te voy a borrar\r\n"
				+ "\r\n"
				+ " el cerito papaar papaar torpedo no puedor ese que llega llevame al sircoo. No puedor\r\n"
				+ "\r\n"
				+ " ese que llega jarl quietooor pupita. Hasta luego Lucas a peich amatomaa mamaar te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa ese hombree. Te voy a borrar el cerito la caidita está la cosa muy malar\r\n"
				+ "\r\n"
				+ " diodeno está la cosa muy malar. Jarl a peich condemor pecador.\r\n"
				+ "\r\n"
				+ "Jarl la caidita de la pradera qué dise usteer sexuarl condemor. Fistro a gramenawer va\r\n"
				+ "\r\n"
				+ " usté muy cargadoo te va a hasé pupitaa diodenoo. Se calle DavidLopez 6ustée al ataquerl se calle\r\n"
				+ "\r\n"
				+ " ustée te voy a borrar el cerito a peich jarl tiene musho peligro papaar papaar de la\r\n"
				+ "\r\n"
				+ " pradera a gramenawer no puedor. Diodeno al ataquerl a wan hasta luego Lucas apetecan\r\n"
				+ "\r\n"
				+ " jarl. Va usté muy cargadoo llevame al sircoo se calle ustée por la gloria de mi madre\r\n"
				+ "\r\n"
				+ " fistro. Jarl a peich no te digo trigo por no llamarte Rodrigor ese hombree la caidita.\r\n"
				+ "\r\n"
				+ " Ahorarr a wan fistro al ataquerl diodenoo ese pedazo de jarl llevame al sircoo.\r\n"
				+ "\r\n"
				+ " Tiene musho peligro mamaar condemor amatomaa me cago en tus muelas torpedo a gramenawer\r\n"
				+ "\r\n"
				+ " tiene musho peligro de la pradera papaar papaar. Pecador pupita mamaar pupita quietooor\r\n"
				+ "\r\n"
				+ " qué dise usteer fistro caballo blanco caballo negroorl papaar papaar.Lorem fistrum diodenoo la caidita a gramenawer la caidita ahorarr a wan.\r\n"
				+ "\r\n"
				+ "Jarl sexuarl a wan me cago en tus muelas te voy a borrar el cerito por la gloria\r\n"
				+ "\r\n"
				+ " de mi madre está la cosa muy malar benemeritaar mamaar va usté muy cargadoo.\r\n"
				+ "\r\n"
				+ " Condemor diodeno jarl no puedor está la cosa muy malar qué dise usteer te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa pecador la caidita qué dise usteer. No te diAgustinArcos 4go trigo por no\r\n"
				+ "\r\n"
				+ " llamarte Rodrigor me cago en tus muelas pupita ahorarr quietooor amatomaa\r\n"
				+ "\r\n"
				+ " ahorarr se calle ustée me cago en tus muelas sexuarl. A gramenawer\r\n"
				+ "\r\n"
				+ " apetecan por la gloria de mi madre me cago en tus muelas pupita. Llevame al sircoo\r\n"
				+ "\r\n"
				+ " te va a hasé pupitaa ahorarr tiene musho peligro qué dise usteer tiene musho\r\n"
				+ "\r\n"
				+ " peligro hasta luego Lucas se calle ustée torpedo. Te va a hasé pupitaa está la\r\n"
				+ "\r\n"
				+ " cosa muy malar amatomaa no te digo trigo por no llamarte Rodrigor ahorarr no puedor\r\n"
				+ "\r\n"
				+ " sexuarl a wan de la pradera la caidita pecador.\r\n"
				+ "\r\n"
				+ "Apetecan a gramenawer está la cosa muy malar llevame al sircoo amatomaa ese pedazo\r\n"
				+ "\r\n"
				+ "de llevame al sircoo. Me cago en tus muelas no puedor ahorarr diodeno te voy a borrar\r\n"
				+ "\r\n"
				+ " el cerito papaar papaar torpedo no puedor ese que llega llevame al sircoo. No puedor\r\n"
				+ "\r\n"
				+ " ese que llega jarl quietooor pupita. Hasta luego LucasAlejandroAsencio 2 a peich amatomaa mamaar te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa ese hombree. Te voy a borrar el cerito la caidita está la cosa muy malar\r\n"
				+ "\r\n"
				+ " diodeno está la cosa muy malar. Jarl a peich condemor pecador.\r\n"
				+ "\r\n"
				+ "Jarl la caidita de la pradera qué dise usteer sexuarl condemor. Fistro a gramenawer va\r\n"
				+ "\r\n"
				+ " usté muy cargadoo te va a hasé pupitaa diodenoo. Se calle ustée al ataquerl se calle\r\n"
				+ "\r\n"
				+ " ustée te voy a borrar el cerito a peich jarl tiene musho peligro papaar papaar de la\r\n"
				+ "\r\n"
				+ " pradera a gramenawer no puedor. Diodeno al ataquerl a wan hasta luego Lucas apetecan\r\n"
				+ "\r\n"
				+ " jarl. Va usté muy cargadoo llevame al sircoo se calle ustée por la gloria de mi madre\r\n"
				+ "\r\n"
				+ " fistro. Jarl a peich no te digo trigo por no llamarte Rodrigor ese hombree la caidita.\r\n"
				+ "\r\n"
				+ " Ahorarr a wan fistro al ataquerl diodenoo ese pedazo de jarl llevame al sircoo.\r\n"
				+ "\r\n"
				+ " Tiene musho peligro mamaar condemor amatomaa me cago en tus muelas torpedo a gramenawer\r\n"
				+ "\r\n"
				+ " tiene musho peligro de la pradera papaar papaar. Pecador pupita mamaar pupita quietooor\r\n"
				+ "\r\n"
				+ " qué dise usteer fistAbelRiquelme 7ro caballo blanco caballo negroorl papaar papaar.Lorem fistrum diodenoo la caidita a gramenawer la caidita ahorarr a wan.\r\n"
				+ "\r\n"
				+ "Jarl sexuarl a wan me cago en tus muelas te voy a borrar el cerito por la gloria\r\n"
				+ "\r\n"
				+ " de mi madre está la cosa muy malar benemeritaar mamaar va usté muy cargadoo.\r\n"
				+ "\r\n"
				+ " Condemor diodeno jarl no puedor está la cosa muy malar qué dise usteer te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa pecador la caidita qué dise usteer. No te ChristianCocargeanu 7digo trigo por no\r\n"
				+ "\r\n"
				+ " llamarte Rodrigor me cago en tus muelas pupita ahorarr quietooor amatomaa\r\n"
				+ "\r\n"
				+ " ahorarr se calle ustée me cago en tus muelas sexuarl. A gramenawer\r\n"
				+ "\r\n"
				+ " apetecan por la gloria de mi madre me cago en tus muelas pupita. Llevame al sircoo\r\n"
				+ "\r\n"
				+ " te va a hasé pupitaa ahorarr tiene musho peligro qué dise usteer tiene musho\r\n"
				+ "\r\n"
				+ " peligro hasta luego Lucas se calle ustée torpedo. Te va a hasé pupitaa está la\r\n"
				+ "\r\n"
				+ " cosa muy malar amatomaa no te digo trigo por no llamarte Rodrigor ahorarr no puedor\r\n"
				+ "\r\n"
				+ " sexuarl a wan de la pradera la caidita pecador.\r\n"
				+ "\r\n"
				+ "Apetecan a gramenawer está la cosa muy malar llevame al sircoo amatomaa ese pedazo\r\n"
				+ "\r\n"
				+ "de llevame al sircoo. Me cago en tus muelas nHugoMarquez 9o puedor ahorarr diodeno te voy a borrar\r\n"
				+ "\r\n"
				+ " el cerito papaar papaar torpedo no puedor ese que llega llevame al sircoo. No puedor\r\n"
				+ "\r\n"
				+ " ese que llega jarl quietooor pupita. Hasta luego Lucas a peich amatomaa mamaar te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa ese hombree. Te voy a borrar el cerito la caidita está la cosa muy malar\r\n"
				+ "\r\n"
				+ " diodeno está la cosa muy malar. Jarl a peich condemor pecador.\r\n"
				+ "\r\n"
				+ "Jarl la caidita de la pradera qué dise usteer sexuarl condemor. Fistro a gramenawer va\r\n"
				+ "\r\n"
				+ " usté muy cargadoo te va a hasé pupitaa diodenoo. Se calle ustée al ataquerl se calle\r\n"
				+ "\r\n"
				+ " ustée te voy a borrar el cerito a peich jarl tiene musho peligro papaar papaar de la\r\n"
				+ "\r\n"
				+ " pradera a gramenawer no puedor. Diodeno al ataquerl a wan hasta luego Lucas apetecan\r\n"
				+ "\r\n"
				+ " jarl. Va usté muy cargadoo llevame al sircoo se calle ustée por la gloria de mi madre\r\n"
				+ "\r\n"
				+ " fistro. Jarl a peich no te digo trigo por no llamarte Rodrigor ese hombree la caidita.\r\n"
				+ "\r\n"
				+ " Ahorarr a wan fistro al ataquerl diodenoo ese pedazo de jarl llevame al sircoo.\r\n"
				+ "\r\n"
				+ " Tiene musho peligro mamaar condemor amatomaa me cago en tus muelas torpedo a gramenawer\r\n"
				+ "\r\n"
				+ " tiene musho peligro de la pradera papaar papaar. JosePonce 7Pecador pupita mamaar pupita quietooor\r\n"
				+ "\r\n"
				+ " qué dise usteer fistro caballo blanco caballo negroorl papaar papaar.Lorem fistrum diodenoo la caidita a gramenawer la caidita ahorarr a wan.\r\n"
				+ "\r\n"
				+ "Jarl sexuarl a wan MiguelParamos 9 me cago en tus muelas te voy a borrar el cerito por la gloria\r\n"
				+ "\r\n"
				+ " de mi madre está la cosa muy malar benemeritaar mamaar va usté muy cargadoo.\r\n"
				+ "\r\n"
				+ " Condemor diodeno jarl no puedor AlejandroBarrionuevo 7está la cosa muy malar qué dise usteer te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa pecador la caidita qué dise usteer. No te digo trigo por no\r\n"
				+ "\r\n"
				+ " llamarte Rodrigor me cago en tus muelas pupita ahorarr quietooor amatomaa\r\n"
				+ "\r\n"
				+ " ahorarr se calle ustée me cago en tus muelas sexuarl. A gramenawer\r\n"
				+ "\r\n"
				+ " apetecan por la gloria de mi madre me cago en tus muelas pupita. Llevame al sircoo\r\n"
				+ "\r\n"
				+ " te va a hasé pupitaa ahorarr tiene musho peligro qué dise usteer tiene musho\r\n"
				+ "\r\n"
				+ " peligro hasta luego Lucas se calle ustée torpedo. Te va a hasé pupitaa está la\r\n"
				+ "\r\n"
				+ " cosa muy malar amatomaa no te digo trigo por no llamarte Rodrigor ahorarr no puedor\r\n"
				+ "\r\n"
				+ " sexuarl a wan de la pradera la caidita pecador.\r\n"
				+ "\r\n"
				+ "Apetecan a gramenawer está la cosa muy malar llevame al sircoo amatomaa ese pedazo\r\n"
				+ "\r\n"
				+ "de llevame al sircoo. Me cago en tGonzaloTroya 5us muelas no puedor ahorarr diodeno te voy a borrar\r\n"
				+ "\r\n"
				+ " el cerito papaar papaar torpedo no puedor ese que llega llevame al sircoo. No puedor\r\n"
				+ "\r\n"
				+ " ese que llega jarl quietooor pupita. Hasta luego Lucas a peich amatomaa mamaar te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa ese hombree. Te voy a borrar el cerito la caidita está la cosa muy malar\r\n"
				+ "\r\n"
				+ " diodeno está la cosa muy malar. Jarl a peich condemor pecador.\r\n"
				+ "\r\n"
				+ "Jarl la caidita de la pradera qué dise usteer sexuarl condemor. Fistro a gramenawer va\r\n"
				+ "\r\n"
				+ " usté muy cargadoo te va a hasé pupitaa diodenoo. Se calle ustée al ataquerl se calle\r\n"
				+ "\r\n"
				+ " ustée te voy a borrar el cerito a peich jarl tiene musho peligro papaar papaar de la\r\n"
				+ "\r\n"
				+ " pradera a gramenawer no puedor. Diodeno alMiguelMarquez 5 ataquerl a wan hasta luego Lucas apetecan\r\n"
				+ "\r\n"
				+ " jarl. Va usté muy cargadoo llevame al sircoo se calle ustée por la gloria de mi madre\r\n"
				+ "\r\n"
				+ " fistro. Jarl a peich no te digo trigo por no llamarte Rodrigor ese hombree la caidita.\r\n"
				+ "\r\n"
				+ " Ahorarr a wan fistro al ataquerl diodenoo ese pedazo de jarl llevame al sircoo.\r\n"
				+ "\r\n"
				+ " Tiene musho peligro mamaar condemor amatomaa me cago en tus muelas torpedo a gramenawer\r\n"
				+ "\r\n"
				+ " tiene musho peligro de la pradera papaar papaar. Pecador pupita mamaar pupita quietooor\r\n"
				+ "\r\n"
				+ " qué dise usteer fistro caballo blanco caballo negroorl papaar papaar.Lorem fistrum diodenoo la caidita a gramenawer la caidita ahorarr a wan.\r\n"
				+ "\r\n"
				+ "Jarl sexuarl a wan me cago en tus muelas te voy a borrar el AlexLopez 6cerito por la gloria\r\n"
				+ "\r\n"
				+ " de mi madre está la cosa muy malar benemeritaar mamaar va usté muy cargadoo.\r\n"
				+ "\r\n"
				+ " Condemor diodeno jarl no puedor está la cosa muy malar qué dise usteer te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa pecador la caidita qué dise usteer. No te digo trigo por no\r\n"
				+ "\r\n"
				+ " llamarte Rodrigor me cago en tus muelas pupita ahorarr quietooor amatomaa\r\n"
				+ "\r\n"
				+ " ahorarr se calle ustée me cago en tus muelas sexuarl. A gramenawer\r\n"
				+ "\r\n"
				+ " apetecan por la gloria dMarcosGarcia 9e mi madre me cago en tus muelas pupita. Llevame al sircoo\r\n"
				+ "\r\n"
				+ " te va a hasé pupitaa ahorarr tiene musho peligro qué dise usteer tiene musho\r\n"
				+ "\r\n"
				+ " peligro hasta luego Lucas se calle ustée torpedo. Te va a hasé pupitaa está la\r\n"
				+ "\r\n"
				+ " cosa muy malar amatomaa no te digo trigo por no llamarte Rodrigor ahorarr no puedor\r\n"
				+ "\r\n"
				+ " sexuarl a wan de la pradera la caidita pecador.\r\n"
				+ "\r\n"
				+ "Apetecan a gramenawer está la cosa muy malar llevame al sircoo amatomaa ese pedazo\r\n"
				+ "\r\n"
				+ "de llevame al sircoo. Me cago en tus muelas no puedor ahorarr diodeno te voy a borrar\r\n"
				+ "\r\n"
				+ " el cerito papaar papaar torpedo no puedor ese que llega llevame al sircoo. No puedor\r\n"
				+ "\r\n"
				+ " ese que llega jarl quietooor pupita. Hasta luego Lucas a peich amatomaa mamaar te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa ese hombree. Te voy a borrar el cerito la caidita está la cosa muy malar\r\n"
				+ "\r\n"
				+ " diodeno está la cosa muy malar. Jarl a peich condemor pecador.\r\n"
				+ "\r\n"
				+ "Jarl la caidita de la pradera qué dise usteer sexuarl JeronimoCasares 7condemor. Fistro a gramenawer va\r\n"
				+ "\r\n"
				+ " usté muy cargadoo te va a hasé pupitaa diodenoo. Se calle ustée al ataquerl se calle\r\n"
				+ "\r\n"
				+ " ustée te voy a borrar el cerito a peich jarl tiene musho peligro papaar papaar de la\r\n"
				+ "\r\n"
				+ " pradera a gramenawer no puedor. Diodeno al ataquerl a wan hasta luego Lucas apetecan\r\n"
				+ "\r\n"
				+ " jarl. Va usté muy cargadoo llevame al AlvaroQuiñones 7sircoo se calle ustée por la gloria de mi madre\r\n"
				+ "\r\n"
				+ " fistro. Jarl a peich no te dJuanmiMoreno 8igo trigo por no llamarte Rodrigor ese hombree la caidita.\r\n"
				+ "\r\n"
				+ " Ahorarr a wan fistro al ataquerl diodenoo ese pedazo de jarl llevame al sircoo.\r\n"
				+ "\r\n"
				+ " Tiene musho peligro mamaar condemor  amatomaa me cago en tus muelas torpedo a gramenawer\r\n"
				+ "\r\n"
				+ " tiene musho peligro de la pradera papaar papaar. Pecador pupita mamaar pupita quietooor\r\n"
				+ "\r\n"
				+ " qué dise usteer fistro caballo blanco caballo negroorl papaar papaar.Lorem fistrum diodenoo la caidita a gramenawer la caidita ahorarr a wan.\r\n"
				+ "\r\n"
				+ "Jarl sexuarl a wan me cago en tus muelas te voy a borrar el JoseCorral 6 cerito por la gloria\r\n"
				+ "\r\n"
				+ " de mi madre está la cosa muy malar benemeritaar mamaar va usté muy cargadoo.\r\n"
				+ "\r\n"
				+ " Condemor diodeno jarl no puedor está la cosa muy malar qué dise usteer te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa pecador la caidita qué IgnacioAranda 7dise usteer. No te digo trigo por no\r\n"
				+ "\r\n"
				+ " llamarte Rodrigor me cago en tus AngelCheca 6muelas pupita ahorarr quietooor amatomaa\r\n"
				+ "\r\n"
				+ " ahorarr se calle ustée me cago en tus muelas sexuarl. A gramenawer\r\n"
				+ "\r\n"
				+ " apetecan por la gloria de mi madre me cago en tus muelas pupita. Llevame al sircoo\r\n"
				+ "\r\n"
				+ " te va a hasé pupitaa ahorarr tiene musho peligro qué dise usteer tiene musho\r\n"
				+ "\r\n"
				+ " peligro hasta luego Lucas se calle ustée torpedo. Te va a hasé pupitaa está la\r\n"
				+ "\r\n"
				+ " cosa muy malar amatomaa no te digo trigo por no llamarte Rodrigor ahorarr no puedor\r\n"
				+ "\r\n"
				+ " sexuarl a wan de la pradera la caidita pecador.\r\n"
				+ "\r\n"
				+ "Apetecan a gramenawer está la cosa muy malar llevame al sircoo amatomaa ese pedazo\r\n"
				+ "\r\n"
				+ "de llevame al sircoo. Me cago en tus muelas no puJoaquinMoreno 7edor ahorarr diodeno te voy a borrar\r\n"
				+ "\r\n"
				+ " el cerito papaar papaar torpedo no puedor ese que llega llevame al sircoo. No puedor\r\n"
				+ "\r\n"
				+ " ese que llega jarl quietooor pupita. Hasta luego Lucas a peich amatomaa mamaar te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa ese hombree. Te voy a borrar el cerito la caidita está la cosa muy malar\r\n"
				+ "\r\n"
				+ " diodeno está la cosa muy malar. Jarl a peich condemor pecador.\r\n"
				+ "\r\n"
				+ "Jarl la caidita de la pradera qué dise usteer sexuarl condemor. Fistro a gramenawer va\r\n"
				+ "\r\n"
				+ " usté muy cargadoo te va a hasé pupitaa diodenoo. Se calle ustée al ataquerl se calle\r\n"
				+ "\r\n"
				+ " ustée te voy a borrar el cerito a peich jarl tiene musho peligro papaar papaar de la\r\n"
				+ "\r\n"
				+ " pradera a gramenawer no puedor. Diodeno al ataquerl a wan hasta luego Lucas apetecan\r\n"
				+ "\r\n"
				+ " jarl. Va usté muy NicoQuecedo 7cargadoo llevame al sircoo se calle ustée por la gloria de mi madre\r\n"
				+ "\r\n"
				+ " fistro. Jarl a peich no te digo trigo por no llamarte Rodrigor ese hombree la caidita.\r\n"
				+ "\r\n"
				+ " Ahorarr a wan fistro al ataquerl diodenoo ese pedazo de jarl llevame al sircoo.\r\n"
				+ "\r\n"
				+ " Tiene musho peligro mamaar condemor amatomaa me cago en tus muelas torpedo a gramenawer\r\n"
				+ "\r\n"
				+ " tiene musho peligro de la pradera papaar papaar. Pecador pupita mamaar pupita quietooor\r\n"
				+ "\r\n"
				+ " qué dise usteer fistro caballo blanco caballo negroorl papaar papaar.Lorem fistrum diodenoo la caidita a gramenawer la caidita ahorarr a wan.\r\n"
				+ "\r\n"
				+ "Jarl sexuarl a wan me cago en tus muelas te voy a borrar el cerito por la gloria\r\n"
				+ "\r\n"
				+ " de mi madre está la cosa muy malar benemeritaar mamaar va usté muy cargadoo.\r\n"
				+ "\r\n"
				+ " Condemor diodeno jarl no puedor está la cosa muy malar qué dise usteer te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa pecador la caidita quéJenaroLeal 6 dise usteer. No te digo trigo por no\r\n"
				+ "\r\n"
				+ " llamarte Rodrigor me cago en tus muelas pupita ahorarr quietooor amatomaa\r\n"
				+ "\r\n"
				+ " ahorarr se calle ustée me cago en tus muelas sexuarl. A gramenawer\r\n"
				+ "\r\n"
				+ " apetecan por la gloria de mi DanielOrdoñez 5madre me cago en tus muelas pupita. Llevame al sircoo\r\n"
				+ "\r\n"
				+ " te va a hasé pupitaa ahorarr tiene musho peligro qué dise usteer tiene musho\r\n"
				+ "\r\n"
				+ " peligro hasta luego Lucas se calle ustée torpedo. Te va a hasé pupitaa está la\r\n"
				+ "\r\n"
				+ " cosa muy malar amatomaa no te digo trigo por no llamarte Rodrigor ahorarr no puedor\r\n"
				+ "\r\n"
				+ " sexuarl a wan de la pradera la caidita pecador.\r\n"
				+ "\r\n"
				+ "Apetecan a gramenawer está la cosa muy malar llevame al sircoo amatomaa ese pedazo\r\n"
				+ "\r\n"
				+ "de llevame al sircoo. Me cago en tus muelas no puedor ahorarr diodeno te voy a borrar\r\n"
				+ "\r\n"
				+ " el cerito papaar papaar torpedo no puedor ese que llega llevame al sircoo. No puedor\r\n"
				+ "\r\n"
				+ " ese que llega jarl quietooor pupita. AntonioTortosa 8Hasta luego Lucas a peich amatomaa mamaar te va a\r\n"
				+ "\r\n"
				+ " hasé pupitaa ese hombree. Te voy a borrar el cerito la caidita está la cosa muy malar\r\n"
				+ "\r\n"
				+ " diodeno está la cosa muy malar. Jarl a peich condemor pecador.\r\n"
				+ "\r\n"
				+ "Jarl la caidita de la pradera qué dise usteer sexuarl condemor. Fistro a gramenawer va\r\n"
				+ "\r\n"
				+ " usté muy cargadoo te va a hasé pupitaa diodenoo. Se calle ustée al ataquerl se calle\r\n"
				+ "\r\n"
				+ " ustée te voy a borrar el cerito a peich jarl tiene musho peligro papaar papaar de la\r\n"
				+ "\r\n"
				+ " pradera a gramenawer no puedor. Diodeno al ataquerl a wan hasta luego Lucas apetecan\r\n"
				+ "\r\n"
				+ " jarl. Va usté muy cargadoo llevame al sircoo se calle ustée por la gloria de mi madre\r\n"
				+ "\r\n"
				+ " fistro. Jarl a peich no te digo trigo por no llamarte Rodrigor ese hombree la caidita.\r\n"
				+ "\r\n"
				+ " Ahorarr a wan fistro al ataquerl diodenoo ese pedazo de jarl llevame al sircoo.\r\n"
				+ "\r\n"
				+ " Tiene musho peligro mamaar condemor amatomaa me cago en tus muelas torpedo a gramenawer\r\n"
				+ "\r\n"
				+ " tiene musho peligro de la pradera papaar papaar. Pecador pupita mamaar pupita quietooor\r\n"
				+ "\r\n"
				+ " qué dise usteer fistro caballo SandraJimenez 8blanco caballo negroorl papaar papaar.”";
		System.out.println("Dime tu nombre (Nico):");
		String nombre = sc.nextLine();
		
		System.out.println("Dime tu apellido(Quecedo):");
		String apellido = sc.nextLine();
		
		String nombreCompleto = nombre + apellido ;
		
		int posicion = tectoCompleto.indexOf(nombreCompleto) ;
		int numeroTexto = posicion + 12;
		
		String numeroNombre = tectoCompleto.substring(numeroTexto, numeroTexto+1);
		int numeroNombreInt = Integer.parseInt(numeroNombre);
		System.out.println("El numero es: "+ numeroNombreInt);
		System.out.println(tectoCompleto.substring(numeroTexto+1, numeroTexto+ numeroNombreInt +1 ));
	}

}
